heroes-db:
  image: postgres:13
  container_name: heroes-db
  ports:
    - "5432"
  environment:
    POSTGRES_PASSWORD: password
  volumes:
    - ../../../rest-heroes/deploy/db-init/initialize-database.sql:/docker-entrypoint-initdb.d/1-init-db.sql
    - ../../../rest-heroes/deploy/db-init/initialize-tables.sql:/docker-entrypoint-initdb.d/2-init-tables.sql